// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CommonReduce from "@/components/common/CommonReduce";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CommonReduce>{children}</CommonReduce>
      </body>
    </html>
  );
}
